### ISSUE TITLE
WIP Roadmap

### ISSUE THREAD

**Issue by ulrokx** [stevensblueprint/aad-admin#100]
Authentication verifies the identity of a user or service, and authorization determines their access rights.
Authorization roles are MENTEE, MENTOR, and ADMIN

Frontend:
- [ ] Pages for non-auth users
  - [ ] Landing page
- [ ] Pages for authenticated users
  - [ ] Directory page
    - [ ] Tab layout
    - [ ] Table for users
  - [ ] Profile pages
    - [ ] Layout and design for profile pages
- [ ] Pages for ADMIN role
  - [ ] Forms
    - [ ] Form creation? (TBD)
    - [ ] Collection manager
    - [ ] Submission viewer
      - [ ] Export all to excel
  - [ ] KPIs
    - [ ] KPI page for forms
